package openguardian4.Gatt.Enum.Implementation;

import openguardian4.Gatt.Enum.IGattEnum;

public enum SocpOpcode implements IGattEnum<Integer> {
    SET_CGM_COMMUNICATION_INTERVAL(1),
    GET_CGM_COMMUNICATION_INTERVAL(2),
    COMMUNICATION_INTERVAL_RESPONSE(3),
    SET_GLUCOSE_CALIBRATION_VALUE(4),
    GET_GLUCOSE_CALIBRATION_VALUE(5),
    CALIBRATION_VALUE_RESPONSE(6),
    RESPONSE(28),
    CONFIGURE_SENSOR(128),
    GET_CALIBRATION_CONTEXT(129),
    CALIBRATION_CONTEXT_RESPONSE(130),
    READ_SESSION_START_TIME(131),
    READ_SESSION_START_TIME_RESPONSE(132),
    SENSOR_INTEGRITY_REQUEST(133),
    SENSOR_INTEGRITY_RESPONSE(134),
    READ_TRANSMITTER_RTC(138),
    READ_TRANSMITTER_RTC_RESPONSE(139),
    READ_CURRENT_SESSION_ID(140),
    READ_CURRENT_SESSION_ID_RESPONSE(141),
    GET_CALIBRATION_DETAILS(142),
    CALIBRATION_DETAILS_RESPONSE(143),
    GET_SENSOR_DETAILS(144),
    SENSOR_DETAILS_RESPONSE(145),
    SET_CALIBRATION_TRANSFER_DATA(146),
    GET_CALIBRATION_TRANSFER_DATA(147),
    GET_CALIBRATION_TRANSFER_DATA_RESPONSE(148),
    GET_CGM_OPERATING_LIMITS(149),
    GET_CGM_OPERATING_LIMITS_RESPONSE(150);

    private final int value;

    SocpOpcode(int i2) {
        this.value = i2;
    }

    /* JADX WARN: Can't rename method to resolve collision */
    @Override // p121e.p414g.p469f.p470a.p512i.p514d.IGattEnum
    public Integer getValue() {
        return Integer.valueOf(this.value);
    }
}